{
    "customProperties":{
        "formComponent":false,
        "useCssPosition":true
    },
    "dataSource":"db:/example_data/orders",
    "encapsulation":108,
    "items":[
        {
            "anchors":3,
            "cssPosition":"187,-1,-1,calc(25% + 176px),180,20",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"20",
                    "left":"calc(25% + 176px)",
                    "right":"-1",
                    "top":"187",
                    "width":"180"
                },
                "location":{
                    "x":319,
                    "y":230
                },
                "size":{
                    "height":20,
                    "width":180
                },
                "styleClassExpression":null,
                "text":"Orderdate",
                "toolTipText":"Orderdate"
            },
            "location":"319,230",
            "name":"label_790",
            "size":"180,20",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"2D63A968-E2F2-499D-940D-80698127B9F8"
        },
        {
            "cssPosition":"304,10,10,calc(25% + 10px),200,100",
            "json":{
                "columns":[
                    {
                        "dataprovider":"productid",
                        "headerTitle":"Product",
                        "id":"productid",
                        "styleClassDataprovider":null,
                        "svyUUID":"01F5E440-CAF3-4C01-8EEB-29862FD7398E",
                        "valuelist":"30282CB5-DA05-4B5D-B761-00A164758B44"
                    },
                    {
                        "dataprovider":"quantity",
                        "headerTitle":"Quantity",
                        "id":"quantity",
                        "maxWidth":150,
                        "styleClassDataprovider":null,
                        "svyUUID":"9375EA19-F6FE-48EA-A4AE-2B9F97619BB7"
                    },
                    {
                        "dataprovider":"unitprice",
                        "format":"¤#.00|#.00",
                        "headerTitle":"UnitPrice",
                        "id":"unitprice",
                        "maxWidth":150,
                        "styleClassDataprovider":null,
                        "svyUUID":"4ADE5575-1ABF-462C-975D-063BB84D4313"
                    },
                    {
                        "dataprovider":"subtotal",
                        "format":"¤#.00|#.00",
                        "headerTitle":"Subtotal",
                        "maxWidth":150,
                        "svyUUID":"DC47B66E-5BF5-454A-8073-CF87768BCD56"
                    }
                ],
                "cssPosition":{
                    "bottom":"10",
                    "height":"100",
                    "left":"calc(25% + 10px)",
                    "right":"10",
                    "top":"304",
                    "width":"200"
                },
                "myFoundset":{
                    "foundsetSelector":"orders_to_order_details"
                }
            },
            "name":"datagrid_1",
            "typeName":"aggrid-groupingtable",
            "typeid":47,
            "uuid":"3AD0300F-7208-4C80-BD3C-D49175B08BA0"
        },
        {
            "anchors":3,
            "cssPosition":"21,-1,-1,calc(25% + 176px),276,30",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"calc(25% + 176px)",
                    "right":"-1",
                    "top":"21",
                    "width":"276"
                },
                "location":{
                    "x":319,
                    "y":64
                },
                "size":{
                    "height":30,
                    "width":276
                },
                "styleClass":"h2",
                "text":"Order #%%orderid%%"
            },
            "location":"319,64",
            "name":"label_3",
            "size":"276,30",
            "styleClass":"h2",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"4A8936E5-F523-414E-AB5B-052353255C82"
        },
        {
            "height":480,
            "partType":5,
            "typeid":19,
            "uuid":"8015396C-6B9D-4BB2-87FA-E7EE4C671847"
        },
        {
            "anchors":3,
            "cssPosition":"67,-1,-1,calc(25% + 176px),180,20",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"20",
                    "left":"calc(25% + 176px)",
                    "right":"-1",
                    "top":"67",
                    "width":"180"
                },
                "location":{
                    "x":319,
                    "y":110
                },
                "size":{
                    "height":20,
                    "width":180
                },
                "styleClassExpression":null,
                "text":"Customer",
                "toolTipText":"Customerid"
            },
            "location":"319,110",
            "name":"label_266",
            "size":"180,20",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"9DA403DF-3789-4257-8D7A-5DA110E8785A"
        },
        {
            "anchors":3,
            "cssPosition":"151,-1,-1,calc(25% + 176px),179,30",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"calc(25% + 176px)",
                    "right":"-1",
                    "top":"151",
                    "width":"179"
                },
                "dataProviderID":"employeeid",
                "location":{
                    "x":319,
                    "y":194
                },
                "size":{
                    "height":30,
                    "width":179
                },
                "styleClass":"default-align",
                "valuelistID":"12062E28-3DEF-4A47-965C-71C7DF53B584"
            },
            "location":"319,194",
            "name":"typeahead_2",
            "size":"179,30",
            "styleClass":"default-align",
            "typeName":"bootstrapcomponents-typeahead",
            "typeid":47,
            "uuid":"A96A3611-FA48-453B-93C7-47E7FB413D76"
        },
        {
            "anchors":3,
            "cssPosition":"92,-1,-1,calc(25% + 176px),179,30",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"calc(25% + 176px)",
                    "right":"-1",
                    "top":"92",
                    "width":"179"
                },
                "dataProviderID":"customerid",
                "location":{
                    "x":319,
                    "y":135
                },
                "size":{
                    "height":30,
                    "width":179
                },
                "styleClass":"default-align",
                "valuelistID":"3076081B-2B1B-458B-9587-0F0332624E4C"
            },
            "location":"319,135",
            "name":"typeahead_1",
            "size":"179,30",
            "styleClass":"default-align",
            "typeName":"bootstrapcomponents-typeahead",
            "typeid":47,
            "uuid":"CF0A1EAE-63F7-41B7-84EF-9A534525EDF3"
        },
        {
            "cssPosition":"45,75%,10,10,-1,100",
            "json":{
                "columns":[
                    {
                        "dataprovider":"orderdate",
                        "format":"yyyy-MM-dd",
                        "headerTitle":"Date",
                        "id":"orderdate",
                        "styleClassDataprovider":null,
                        "svyUUID":"CE6B6ED2-4A76-44C8-921F-AFEF7A9CF9D2"
                    },
                    {
                        "dataprovider":"orders_to_customers.companyname",
                        "headerTitle":"Customer",
                        "id":"orders_to_customers.companyname",
                        "styleClassDataprovider":null,
                        "svyUUID":"8805E9A8-E8A4-4FA5-A9A0-1938078D6F69"
                    },
                    {
                        "dataprovider":"shipcity",
                        "headerTitle":"City",
                        "id":"shipcity",
                        "styleClassDataprovider":null,
                        "svyUUID":"1E81B53D-675F-4BD2-B737-C9EBE327D790"
                    }
                ],
                "cssPosition":{
                    "bottom":"10",
                    "height":"100",
                    "left":"10",
                    "right":"75%",
                    "top":"45",
                    "width":"-1"
                },
                "location":{
                    "x":23,
                    "y":238
                },
                "size":{
                    "height":123,
                    "width":302
                }
            },
            "location":"23,238",
            "name":"datagrid_4",
            "size":"302,123",
            "typeName":"aggrid-groupingtable",
            "typeid":47,
            "uuid":"CFC8B2B2-882F-4EF1-8EE0-B74B970D6C17"
        },
        {
            "anchors":3,
            "cssPosition":"207,-1,-1,calc(25% + 176px),180,30",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"calc(25% + 176px)",
                    "right":"-1",
                    "top":"207",
                    "width":"180"
                },
                "dataProviderID":"orderdate",
                "format":"yyyy-MM-dd|mask",
                "location":{
                    "x":319,
                    "y":250
                },
                "size":{
                    "height":30,
                    "width":180
                },
                "styleClass":"default-align"
            },
            "location":"319,250",
            "name":"calendar_426",
            "size":"180,30",
            "styleClass":"default-align",
            "typeName":"bootstrapcomponents-calendar",
            "typeid":47,
            "uuid":"D5330C82-37F6-4D86-8E15-291C5832467C"
        },
        {
            "anchors":3,
            "cssPosition":"127,-1,-1,calc(25% + 176px),180,20",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"20",
                    "left":"calc(25% + 176px)",
                    "right":"-1",
                    "top":"127",
                    "width":"180"
                },
                "location":{
                    "x":319,
                    "y":170
                },
                "size":{
                    "height":20,
                    "width":180
                },
                "styleClassExpression":null,
                "text":"Employee",
                "toolTipText":"Employeeid"
            },
            "location":"319,170",
            "name":"label_588",
            "size":"180,20",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"DA1BA0C3-26F8-4ED3-A88F-A3401917AADE"
        }
    ],
    "name":"orders",
    "navigatorID":"-1",
    "showInMenu":true,
    "typeid":3,
    "uuid":"4E5D8FAC-E4EF-4BC6-8E24-038EBD923CDF"
}