{
    "customProperties":{
        "formComponent":false,
        "useCssPosition":true
    },
    "dataSource":"db:/example_data/orders",
    "encapsulation":108,
    "items":[
        {
            "anchors":3,
            "cssPosition":"115,-1,-1,calc( 25% + 200px),179,30",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"calc( 25% + 200px)",
                    "right":"-1",
                    "top":"115",
                    "width":"179"
                },
                "dataProviderID":"shipaddress",
                "location":{
                    "x":319,
                    "y":135
                },
                "size":{
                    "height":30,
                    "width":179
                },
                "styleClass":"default-align",
                "valuelistID":"3076081B-2B1B-458B-9587-0F0332624E4C"
            },
            "location":"319,135",
            "name":"typeahead_1_copy14",
            "size":"179,30",
            "styleClass":"default-align",
            "typeName":"bootstrapcomponents-typeahead",
            "typeid":47,
            "uuid":"00799E1E-FCA0-4E97-901C-2C48E675308C"
        },
        {
            "anchors":3,
            "cssPosition":"270,246,-1,-1,80,30",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"-1",
                    "right":"246",
                    "top":"270",
                    "width":"80"
                },
                "location":{
                    "x":319,
                    "y":170
                },
                "size":{
                    "height":20,
                    "width":180
                },
                "styleClassExpression":null,
                "text":"Order Total",
                "toolTipText":"Employeeid"
            },
            "location":"319,170",
            "name":"label_588_copy317_copy406_copy340",
            "size":"180,20",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"13481FB8-3ECA-4A42-8291-4C07684A9191"
        },
        {
            "anchors":3,
            "cssPosition":"90,-1,-1,calc( 25% + 200px),180,20",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"20",
                    "left":"calc( 25% + 200px)",
                    "right":"-1",
                    "top":"90",
                    "width":"180"
                },
                "location":{
                    "x":319,
                    "y":110
                },
                "size":{
                    "height":20,
                    "width":180
                },
                "styleClassExpression":null,
                "text":"Ship Address",
                "toolTipText":"Customerid"
            },
            "location":"319,110",
            "name":"label_266_copy682",
            "size":"180,20",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"2B491FA5-45AE-41A1-9BA9-228C6838524F"
        },
        {
            "anchors":3,
            "cssPosition":"210,-1,-1,calc(25% + 10px),180,20",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"20",
                    "left":"calc(25% + 10px)",
                    "right":"-1",
                    "top":"210",
                    "width":"180"
                },
                "location":{
                    "x":319,
                    "y":230
                },
                "size":{
                    "height":20,
                    "width":180
                },
                "styleClassExpression":null,
                "text":"Orderdate",
                "toolTipText":"Orderdate"
            },
            "location":"319,230",
            "name":"label_790",
            "size":"180,20",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"2D63A968-E2F2-499D-940D-80698127B9F8"
        },
        {
            "cssPosition":"304,10,10,calc(25% + 10px),200,100",
            "json":{
                "columns":[
                    {
                        "dataprovider":"productid",
                        "editType":"TYPEAHEAD",
                        "headerTitle":"Product",
                        "id":"productid",
                        "styleClassDataprovider":null,
                        "svyUUID":"01F5E440-CAF3-4C01-8EEB-29862FD7398E",
                        "valuelist":"30282CB5-DA05-4B5D-B761-00A164758B44"
                    },
                    {
                        "dataprovider":"quantity",
                        "editType":"TEXTFIELD",
                        "headerTitle":"Quantity",
                        "id":"quantity",
                        "maxWidth":150,
                        "styleClassDataprovider":null,
                        "svyUUID":"9375EA19-F6FE-48EA-A4AE-2B9F97619BB7"
                    },
                    {
                        "dataprovider":"unitprice",
                        "editType":"TEXTFIELD",
                        "filterType":null,
                        "format":"¤#.00|#.00",
                        "headerTitle":"UnitPrice",
                        "id":"unitprice",
                        "maxWidth":150,
                        "styleClassDataprovider":null,
                        "svyUUID":"4ADE5575-1ABF-462C-975D-063BB84D4313"
                    },
                    {
                        "dataprovider":"subtotal",
                        "format":"¤#.00|#.00",
                        "headerTitle":"Subtotal",
                        "maxWidth":150,
                        "svyUUID":"DC47B66E-5BF5-454A-8073-CF87768BCD56"
                    }
                ],
                "cssPosition":{
                    "bottom":"10",
                    "height":"100",
                    "left":"calc(25% + 10px)",
                    "right":"10",
                    "top":"304",
                    "width":"200"
                },
                "myFoundset":{
                    "foundsetSelector":"orders_to_order_details"
                },
                "onColumnDataChange":"CBCF8530-4ED7-4B8B-8086-E4D068B63C2D"
            },
            "name":"datagrid_1",
            "typeName":"aggrid-groupingtable",
            "typeid":47,
            "uuid":"3AD0300F-7208-4C80-BD3C-D49175B08BA0"
        },
        {
            "cssPosition":"45,10,-1,-1,103,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"-1",
                    "right":"10",
                    "top":"45",
                    "width":"103"
                },
                "onActionMethodID":"FD52D816-1E0D-4239-8AF2-F8E54E80B9C3",
                "text":"New order"
            },
            "name":"button_1",
            "typeName":"bootstrapcomponents-button",
            "typeid":47,
            "uuid":"4682145B-ED45-464C-9B84-3516EDE75CD8"
        },
        {
            "anchors":3,
            "cssPosition":"46,-1,-1,calc(25% + 10px),276,30",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"calc(25% + 10px)",
                    "right":"-1",
                    "top":"46",
                    "width":"276"
                },
                "location":{
                    "x":319,
                    "y":64
                },
                "size":{
                    "height":30,
                    "width":276
                },
                "styleClass":"h2",
                "text":"Order #%%orderid%%"
            },
            "location":"319,64",
            "name":"label_3",
            "size":"276,30",
            "styleClass":"h2",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"4A8936E5-F523-414E-AB5B-052353255C82"
        },
        {
            "anchors":3,
            "cssPosition":"150,-1,-1,calc( 25% + 200px),180,20",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"20",
                    "left":"calc( 25% + 200px)",
                    "right":"-1",
                    "top":"150",
                    "width":"180"
                },
                "location":{
                    "x":319,
                    "y":170
                },
                "size":{
                    "height":20,
                    "width":180
                },
                "styleClassExpression":null,
                "text":"Ship City",
                "toolTipText":"Employeeid"
            },
            "location":"319,170",
            "name":"label_588_copy317",
            "size":"180,20",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"5934D222-F9BB-468C-96B6-0B3DCC7742EE"
        },
        {
            "anchors":3,
            "cssPosition":"174,-1,-1,calc( 25% + 200px),179,30",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"calc( 25% + 200px)",
                    "right":"-1",
                    "top":"174",
                    "width":"179"
                },
                "dataProviderID":"shipcity",
                "location":{
                    "x":319,
                    "y":194
                },
                "size":{
                    "height":30,
                    "width":179
                },
                "styleClass":"default-align",
                "valuelistID":"12062E28-3DEF-4A47-965C-71C7DF53B584"
            },
            "location":"319,194",
            "name":"typeahead_2_copy705",
            "size":"179,30",
            "styleClass":"default-align",
            "typeName":"bootstrapcomponents-typeahead",
            "typeid":47,
            "uuid":"5D8E172F-8E77-43D1-A78E-2DC1FA56E95C"
        },
        {
            "anchors":3,
            "cssPosition":"230,-1,-1,calc( 25% + 200px),179,30",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"calc( 25% + 200px)",
                    "right":"-1",
                    "top":"230",
                    "width":"179"
                },
                "dataProviderID":"shipcountry",
                "location":{
                    "x":319,
                    "y":194
                },
                "size":{
                    "height":30,
                    "width":179
                },
                "styleClass":"default-align",
                "valuelistID":"12062E28-3DEF-4A47-965C-71C7DF53B584"
            },
            "location":"319,194",
            "name":"typeahead_2_copy705_copy865",
            "size":"179,30",
            "styleClass":"default-align",
            "typeName":"bootstrapcomponents-typeahead",
            "typeid":47,
            "uuid":"71756573-BD16-4014-AD87-90983B07EF51"
        },
        {
            "height":480,
            "partType":5,
            "typeid":19,
            "uuid":"8015396C-6B9D-4BB2-87FA-E7EE4C671847"
        },
        {
            "cssPosition":"10,75%,-1,10,140,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"10",
                    "right":"75%",
                    "top":"10",
                    "width":"140"
                },
                "dataProviderID":"searchText",
                "onActionMethodID":"B917B183-EF1C-4C78-839D-7BAA03114A94",
                "placeholderText":"Enter Search Criteria"
            },
            "name":"textbox_4",
            "typeName":"bootstrapcomponents-textbox",
            "typeid":47,
            "uuid":"98B5CB54-B0C3-42A2-969F-6661610CA385"
        },
        {
            "anchors":3,
            "cssPosition":"90,-1,-1,calc(25% + 10px),180,20",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"20",
                    "left":"calc(25% + 10px)",
                    "right":"-1",
                    "top":"90",
                    "width":"180"
                },
                "location":{
                    "x":319,
                    "y":110
                },
                "size":{
                    "height":20,
                    "width":180
                },
                "styleClassExpression":null,
                "text":"Customer",
                "toolTipText":"Customerid"
            },
            "location":"319,110",
            "name":"label_266",
            "size":"180,20",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"9DA403DF-3789-4257-8D7A-5DA110E8785A"
        },
        {
            "anchors":3,
            "cssPosition":"174,-1,-1,calc(25% + 10px),179,30",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"calc(25% + 10px)",
                    "right":"-1",
                    "top":"174",
                    "width":"179"
                },
                "dataProviderID":"employeeid",
                "location":{
                    "x":319,
                    "y":194
                },
                "size":{
                    "height":30,
                    "width":179
                },
                "styleClass":"default-align",
                "valuelistID":"12062E28-3DEF-4A47-965C-71C7DF53B584"
            },
            "location":"319,194",
            "name":"typeahead_2",
            "size":"179,30",
            "styleClass":"default-align",
            "typeName":"bootstrapcomponents-typeahead",
            "typeid":47,
            "uuid":"A96A3611-FA48-453B-93C7-47E7FB413D76"
        },
        {
            "cssPosition":"86,-1,-1,calc(25% + 390px),200,170",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"170",
                    "left":"calc(25% + 390px)",
                    "right":"-1",
                    "top":"86",
                    "width":"200"
                },
                "foundset":{
                    "dataproviders":{
                        "label":"order_details_to_products.productname",
                        "value":"subtotal"
                    },
                    "foundsetSelector":"orders_to_order_details"
                },
                "type":"doughnut"
            },
            "name":"chart_5",
            "typeName":"svychartjs-chart",
            "typeid":47,
            "uuid":"AC87F049-C5E3-4BC8-BBD7-5AF654FC48EB"
        },
        {
            "cssPosition":"275,101,-1,-1,150,35",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"35",
                    "left":"-1",
                    "right":"101",
                    "top":"275",
                    "width":"150"
                },
                "dataProviderID":"order_total",
                "format":"¤#,##0.00",
                "showAs":"text",
                "styleClass":"font-weight-bold"
            },
            "name":"datalabel_3",
            "styleClass":"font-weight-bold",
            "typeName":"bootstrapcomponents-datalabel",
            "typeid":47,
            "uuid":"ACC7C57B-D0B2-4746-B108-045668D49ED9"
        },
        {
            "cssPosition":"270,10,-1,-1,100,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"-1",
                    "right":"10",
                    "top":"270",
                    "width":"100"
                },
                "onActionMethodID":"B66CFE39-0DE9-476A-A0D4-B0AF28FC8AC1",
                "text":"Add Item"
            },
            "name":"button_1_copy801",
            "typeName":"bootstrapcomponents-button",
            "typeid":47,
            "uuid":"C3C856C9-6B11-43BD-96ED-25DBC1F7D877"
        },
        {
            "anchors":3,
            "cssPosition":"115,-1,-1,calc(25% + 10px),179,30",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"calc(25% + 10px)",
                    "right":"-1",
                    "top":"115",
                    "width":"179"
                },
                "dataProviderID":"customerid",
                "location":{
                    "x":319,
                    "y":135
                },
                "onDataChangeMethodID":"84BC9BBB-62C3-446B-904E-AC433130DC61",
                "size":{
                    "height":30,
                    "width":179
                },
                "styleClass":"default-align",
                "valuelistID":"3076081B-2B1B-458B-9587-0F0332624E4C"
            },
            "location":"319,135",
            "name":"typeahead_1",
            "size":"179,30",
            "styleClass":"default-align",
            "typeName":"bootstrapcomponents-typeahead",
            "typeid":47,
            "uuid":"CF0A1EAE-63F7-41B7-84EF-9A534525EDF3"
        },
        {
            "cssPosition":"45,75%,10,10,-1,100",
            "json":{
                "columns":[
                    {
                        "dataprovider":"orderdate",
                        "format":"yyyy-MM-dd",
                        "headerTitle":"Date",
                        "id":"orderdate",
                        "styleClassDataprovider":null,
                        "svyUUID":"CE6B6ED2-4A76-44C8-921F-AFEF7A9CF9D2"
                    },
                    {
                        "dataprovider":"orders_to_customers.companyname",
                        "headerTitle":"Customer",
                        "id":"orders_to_customers.companyname",
                        "styleClassDataprovider":null,
                        "svyUUID":"8805E9A8-E8A4-4FA5-A9A0-1938078D6F69"
                    },
                    {
                        "dataprovider":"shipcity",
                        "headerTitle":"City",
                        "id":"shipcity",
                        "styleClassDataprovider":null,
                        "svyUUID":"1E81B53D-675F-4BD2-B737-C9EBE327D790"
                    }
                ],
                "cssPosition":{
                    "bottom":"10",
                    "height":"100",
                    "left":"10",
                    "right":"75%",
                    "top":"45",
                    "width":"-1"
                },
                "location":{
                    "x":23,
                    "y":238
                },
                "size":{
                    "height":123,
                    "width":302
                }
            },
            "location":"23,238",
            "name":"datagrid_4",
            "size":"302,123",
            "typeName":"aggrid-groupingtable",
            "typeid":47,
            "uuid":"CFC8B2B2-882F-4EF1-8EE0-B74B970D6C17"
        },
        {
            "anchors":3,
            "cssPosition":"210,-1,-1,calc(25% + 200px),178,20",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"20",
                    "left":"calc(25% + 200px)",
                    "right":"-1",
                    "top":"210",
                    "width":"178"
                },
                "location":{
                    "x":319,
                    "y":170
                },
                "size":{
                    "height":20,
                    "width":180
                },
                "styleClassExpression":null,
                "text":"Ship Country",
                "toolTipText":"Employeeid"
            },
            "location":"319,170",
            "name":"label_588_copy317_copy406",
            "size":"180,20",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"D038FD91-EB5F-431D-AF2E-514E3E9D94A6"
        },
        {
            "anchors":3,
            "cssPosition":"230,-1,-1,calc(25% + 10px),180,30",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"calc(25% + 10px)",
                    "right":"-1",
                    "top":"230",
                    "width":"180"
                },
                "dataProviderID":"orderdate",
                "format":"yyyy-MM-dd|mask",
                "location":{
                    "x":319,
                    "y":250
                },
                "size":{
                    "height":30,
                    "width":180
                },
                "styleClass":"default-align"
            },
            "location":"319,250",
            "name":"calendar_426",
            "size":"180,30",
            "styleClass":"default-align",
            "typeName":"bootstrapcomponents-calendar",
            "typeid":47,
            "uuid":"D5330C82-37F6-4D86-8E15-291C5832467C"
        },
        {
            "anchors":3,
            "cssPosition":"150,-1,-1,calc(25% + 10px),180,20",
            "json":{
                "anchors":3,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"20",
                    "left":"calc(25% + 10px)",
                    "right":"-1",
                    "top":"150",
                    "width":"180"
                },
                "location":{
                    "x":319,
                    "y":170
                },
                "size":{
                    "height":20,
                    "width":180
                },
                "styleClassExpression":null,
                "text":"Employee",
                "toolTipText":"Employeeid"
            },
            "location":"319,170",
            "name":"label_588",
            "size":"180,20",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"DA1BA0C3-26F8-4ED3-A88F-A3401917AADE"
        }
    ],
    "name":"orders",
    "navigatorID":"-1",
    "showInMenu":true,
    "typeid":3,
    "uuid":"4E5D8FAC-E4EF-4BC6-8E24-038EBD923CDF"
}